<a href="https://colab.research.google.com/github/HemanNiroula/ai-course/blob/main/Worksheet_1_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Numpy

In [5]:
import numpy as np


In [6]:
#Task1 (a)

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Task1 (b)
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#Task1(c)
R = np.random.rand(4,4) # random 4X4 (values 0-1)
R


array([[0.0695232 , 0.93342345, 0.51387357, 0.86906932],
       [0.89390204, 0.64130359, 0.59731135, 0.79674761],
       [0.00973828, 0.05718835, 0.4721756 , 0.97230576],
       [0.82776816, 0.65886158, 0.75419596, 0.26226245]])

# Task 2

In [9]:
#(a)
A_plus_I = A + I
A_plus_I


array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [10]:
#(b)
A_minus_I = A - I
A_minus_I


array([[0., 2., 3.],
       [4., 4., 6.],
       [7., 8., 8.]])

In [11]:
#(c)
A_mul_I = A @ I
A_mul_I


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
#(d)
A_elem = A * I
A_elem



array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

# Task 3

In [13]:
#(a)
A_T = A.T
A_T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
#(b)
det_A = np.linalg.det(A)
det_A


np.float64(0.0)

In [15]:
#(c)
rank_A = np.linalg.matrix_rank(A)
rank_A


np.int64(2)

# Task4

In [16]:
#(a)
D = np.diag([5,10,15])
D


array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 15]])

In [17]:
#(b)
diag_A = np.diag(A)
diag_A


array([1, 5, 9])

In [18]:
#(C)
Z = np.zeros((5,5))
np.fill_diagonal(Z,1)
Z


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Task 5

In [19]:
A2 = np.array([
    [2,1],
    [1,3]
])

b2 = np.array([8,13])

x = np.linalg.solve(A2, b2)
x


array([2.2, 3.6])

# Task6

In [20]:
#(a)
A2_inv = np.linalg.inv(A2)
A2_inv


array([[ 0.6, -0.2],
       [-0.2,  0.4]])

In [21]:
#(b)
check = A2_inv @ A2
check


array([[ 1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

## Task 7

In [22]:
eigvals, eigvecs = np.linalg.eig(A2)
eigvals, eigvecs


(array([1.38196601, 3.61803399]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

# Task 8

In [23]:
#(a)
A_flat = A.flatten()
A_flat


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#(b)
A_reshaped = A.reshape(1,9)
A_reshaped


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Task 9

In [25]:
#(a)
A_first2 = A[:2,:]
A_first2


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#(b)
A_last2 = A[1:,:]
A_last2

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
#(c)
middle = A[1,1]
middle


np.int64(5)

# Task 10

In [29]:
V = np.vstack((A,I))
V


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
H = np.hstack((A,I))
H


array([[1., 2., 3., 1., 0., 0.],
       [4., 5., 6., 0., 1., 0.],
       [7., 8., 9., 0., 0., 1.]])